apiVersion: v1
kind: Service
metadata:
  name: shop-monitor
  namespace: default
spec:
  selector:
    app: shop-monitor
  ports:
    - port: 80
      targetPort: 8000
  # Zmien na LoadBalancer jesli chcesz dostep z zewnatrz klastra
  type: ClusterIP
